import "./dist/bootstrap/bootstrap.min.css";
import "./css/my.css";
import "./css/style.css";
import "./globals.css";
import "./css/responsive.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="" type="image/x-icon" /> */}
        {/* <!-- icon --> */}
        {/* <!-- remix-icon-css-cdn --> */}
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.6.0/fonts/remixicon.css" rel="stylesheet" />
        {/* <!-- font-awesome-icon-css-cdn --> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossOrigin="anonymous" referrerpolicy="no-referrer"/> */}
        {/* <!-- box-icon --> */}
        <link rel="stylesheet" href="./dist/box-icon/boxicons.min.css" />
        {/* <!------------------------------- --> */}

        {/* <!-- font--> */}
        {/* <!-- google-font Roboto and Rubik--> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,900&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        {/* <!------------------------------- --> */}

        {/* <!-- compalsory --> */}
        {/* <!-- bootstrap-css --> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </head>
      <body>
        {children}

        {/* <!-- TODO: Lodash --> */}
        <script src="
    https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js
    "></script>
        {/* <!-- bootstrap-js --> */}
        <script src="./dist/bootstrap/jquery-3.2.1.slim.min.js"></script>
        <script src="./dist/bootstrap/popper.min.js"></script>
        <script src="./dist/bootstrap/bootstrap.min.js"></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
        ></script>
        {/* <!-- jquery code-js --> */}
        <script src="./dist/jquery/jquery-3.7.1.min.js"></script>
        {/* <!-- Custom-js --> */}
        <script src="./js/main.js"></script>
      </body>
    </html>
  );
}
